// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pgzzboopvmglrejenqto.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBnenpib29wdm1nbHJlamVucXRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNTg2MjIsImV4cCI6MjA2NzgzNDYyMn0.LDv_TomKY2dWKFdnMmMizjYsrFXOpLS3gBj3iqWREdk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});